apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development
  team: devops-training

replicas:
- name: api
  count: 1
- name: frontend
  count: 1

images:
- name: my-api
  newTag: "1.0-dev"
- name: my-frontend
  newTag: "1.0-dev"

configMapGenerator:
- name: api-config
  behavior: merge
  literals:
  - FLASK_ENV=development
  - LOG_LEVEL=DEBUG
