apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: gitops-demo
  labels:
    app: gitops-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: gitops-app

---
apiVersion: v1
kind: Service
metadata:
  name: gitops-app-nodeport
  namespace: gitops-demo
  labels:
    app: gitops-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
  selector:
    app: gitops-app
