apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: config-demo
  app.kubernetes.io/part-of: config-management-demo

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: config-demo
  newName: config-demo
  newTag: latest
