apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- toYaml .Values.global.labels | nindent 4 }}
data:
  environment: {{ .Values.global.environment }}
  frontend-port: "{{ .Values.frontend.service.port }}"
  backend-port: "{{ .Values.backend.service.port }}"
  database-host: "{{ .Values.postgresql.service.type }}"
  database-port: "{{ .Values.postgresql.service.port }}"
  database-name: "{{ .Values.postgresql.auth.database }}"
  database-user: "{{ .Values.postgresql.auth.username }}"
