apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.secretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- toYaml .Values.global.labels | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc }}
  username: {{ .Values.postgresql.auth.username | b64enc }}
  database: {{ .Values.postgresql.auth.database | b64enc }}
