apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres-secure-password-2026"
  POSTGRES_REPLICATION_PASSWORD: "replication-password-2026"
