---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: app-namespace
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: app-namespace
  labels:
    app: flask
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: flask

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app-namespace
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: nginx
