{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multitier.fullname" . }}-secret
  labels:
    {{- include "multitier.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-user: {{ .Values.database.auth.username | b64enc | quote }}
  db-password: {{ .Values.database.auth.password | b64enc | quote }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
{{- end }}
