apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - api-configmap.yaml
  - api-hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize

images:
  - name: my-api
    newName: my-api
    newTag: "1.0"
  - name: my-frontend
    newName: my-frontend
    newTag: "1.0"
