apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.secretPasswordKey }}: "postgres123"
  DATABASE_PASSWORD: "postgres123"
