global:
  scrape_interval: 15s      # Collecte des métriques toutes les 15 secondes
  evaluation_interval: 15s  # Évaluation des règles toutes les 15 secondes
  external_labels:
    monitor: 'devops-stack'

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application Flask
  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Node Exporter (métriques système)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
