#!/bin/bash

# AppRole Authentication Example
# Demonstrates how applications authenticate to Vault using AppRole

set -e

VAULT_ADDR="http://localhost:8200"
ROOT_TOKEN="myroot"

echo "=== AppRole Authentication Example ==="
echo ""
echo "This example shows how to:"
echo "1. Get AppRole credentials"
echo "2. Authenticate as an application"
echo "3. Access secrets with the app token"
echo ""

# Step 1: Get the Role ID (usually baked into the app)
echo "[Step 1] Getting Role ID..."
ROLE_ID=$(curl -s -H "X-Vault-Token: $ROOT_TOKEN" \
    "$VAULT_ADDR/v1/auth/approle/role/demo-app/role-id" \
    | grep -o '"role_id":"[^"]*"' | cut -d'"' -f4)

echo "Role ID: $ROLE_ID"
echo ""

# Step 2: Generate a Secret ID (in production, this is generated by CI/CD)
echo "[Step 2] Generating Secret ID..."
SECRET_ID=$(curl -s -X POST -H "X-Vault-Token: $ROOT_TOKEN" \
    "$VAULT_ADDR/v1/auth/approle/role/demo-app/secret-id" \
    | grep -o '"secret_id":"[^"]*"' | cut -d'"' -f4)

echo "Secret ID: $SECRET_ID"
echo ""

# Step 3: Authenticate with Vault using AppRole
echo "[Step 3] Authenticating with AppRole..."
AUTH_RESPONSE=$(curl -s -X POST \
    -H "Content-Type: application/json" \
    -d "{\"role_id\":\"$ROLE_ID\",\"secret_id\":\"$SECRET_ID\"}" \
    "$VAULT_ADDR/v1/auth/approle/login")

APP_TOKEN=$(echo "$AUTH_RESPONSE" | grep -o '"client_token":"[^"]*"' | cut -d'"' -f4)
TOKEN_LEASE=$(echo "$AUTH_RESPONSE" | grep -o '"lease_duration":[0-9]*' | cut -d: -f2)

echo "App Token: $APP_TOKEN"
echo "Token TTL: ${TOKEN_LEASE}s"
echo ""

# Step 4: Use the app token to access secrets
echo "[Step 4] Accessing secrets with app token..."
echo ""

echo "Reading database credentials..."
curl -s -H "X-Vault-Token: $APP_TOKEN" \
    "$VAULT_ADDR/v1/kv/data/secret/database" | jq '.data.data'

echo ""
echo "[Example Complete]"
echo "The application now has:"
echo "- A valid Vault token"
echo "- TTL of ${TOKEN_LEASE}s (auto-renew before expiration)"
echo "- Access to secrets with 'readonly' policy"
