---
all:
  vars:
    ansible_user: devops
    ansible_password: devops
    ansible_become_password: devops
    ansible_connection: ssh
    ansible_port: 22
  children:
    webservers:
      hosts:
        web1.example.com:
          ansible_host: 192.168.1.100
        web2.example.com:
          ansible_host: 192.168.1.101
    dbservers:
      hosts:
        db1.example.com:
          ansible_host: 192.168.1.200
    monitoring:
      hosts:
        mon1.example.com:
          ansible_host: 192.168.1.150
