---
# Handlers pour le rôle webserver

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  listen: Restart nginx

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  listen: Reload nginx
