apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

bases:
- ../../base

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml

replicas:
- name: config-demo
  count: 3

commonLabels:
  environment: production

commonAnnotations:
  environment.info: "Production environment - mission critical"
  owner: "DevOps Team"
  security-level: "high"
