apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app-chart.fullname" . }}-config
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  BACKEND_SERVICE: {{ .Values.backend.name }}
  DATABASE_SERVICE: {{ .Values.database.name }}
  FRONTEND_PORT: {{ .Values.frontend.port | quote }}
  BACKEND_PORT: {{ .Values.backend.port | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
