{{- if .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}-pvc
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
    app: {{ .Values.database.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- end }}
