apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
    app: {{ .Values.database.name }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Values.database.name }}
