apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app-chart.fullname" . }}-secrets
  namespace: {{ include "my-app-chart.namespace" . }}
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
