# Cache Server Configuration
# Generated by Terraform
# Environment: ${environment}

# Connection Settings
host=${cache_host}
port=${cache_port}
environment=${environment}

# Redis Configuration
databases=16
save_enabled=true
save_interval=900
save_changes=1

# Memory Management
maxmemory=512mb
maxmemory_policy=allkeys-lru
memory_optimization=true

# Persistence
appendonly=yes
appendfsync=everysec
auto_aof_rewrite_percentage=100
auto_aof_rewrite_min_size=64mb

# Replication
replication_enabled=true
min_slaves_to_write=1
min_slaves_max_lag=10

# Security
requirepass=disabled
# In production, set proper authentication
# requirepass=<strong_password>

# Monitoring & Logging
loglevel=notice
logfile=/var/log/redis/redis-server.log
