# Database Configuration
# Generated by Terraform
# Environment: ${environment}

# Connection Settings
db_host=${db_host}
db_port=${db_port}
db_name=${db_name}

# Connection Pool
pool_size=20
max_overflow=40
pool_recycle=3600
pool_pre_ping=true

# Performance Tuning
max_connections=100
shared_buffers=256MB
effective_cache_size=1GB
maintenance_work_mem=64MB
checkpoint_completion_target=0.9
wal_buffers=16MB
default_statistics_target=100

# Replication Settings
wal_level=replica
max_wal_senders=10
wal_keep_size=1GB

# Backup Configuration
backup_enabled=true
backup_interval=24h
retention_days=30

# Monitoring
log_statement=all
log_duration=true
log_min_duration_statement=1000
