# Web Server Configuration
# Generated by Terraform
# Environment: ${environment}

# Server Configuration
server_name=${server_name}
port=${port}
environment=${environment}

# Security Settings
ssl_enabled=true
ssl_certificate=/etc/ssl/certs/server.crt
ssl_key=/etc/ssl/private/server.key

# Performance Settings
worker_processes=auto
keepalive_timeout=65
client_max_body_size=100M

# Logging
access_log=/var/log/nginx/access.log
error_log=/var/log/nginx/error.log
log_format combined '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';

# Caching
proxy_cache_valid 200 10m;
proxy_cache_valid 404 1m;

# Headers
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
